//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripBookingWebApp.FindVacationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FindVacationService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Getvactionspot", ReplyAction="http://tempuri.org/IService1/GetvactionspotResponse")]
        decimal[] Getvactionspot(decimal longitude, decimal langitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Getvactionspot", ReplyAction="http://tempuri.org/IService1/GetvactionspotResponse")]
        System.Threading.Tasks.Task<decimal[]> GetvactionspotAsync(decimal longitude, decimal langitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Combine", ReplyAction="http://tempuri.org/IService1/CombineResponse")]
        double Combine(double Relaxvalue, int Safetyvalue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Combine", ReplyAction="http://tempuri.org/IService1/CombineResponse")]
        System.Threading.Tasks.Task<double> CombineAsync(double Relaxvalue, int Safetyvalue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TripBookingWebApp.FindVacationService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TripBookingWebApp.FindVacationService.IService1>, TripBookingWebApp.FindVacationService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal[] Getvactionspot(decimal longitude, decimal langitude) {
            return base.Channel.Getvactionspot(longitude, langitude);
        }
        
        public System.Threading.Tasks.Task<decimal[]> GetvactionspotAsync(decimal longitude, decimal langitude) {
            return base.Channel.GetvactionspotAsync(longitude, langitude);
        }
        
        public double Combine(double Relaxvalue, int Safetyvalue) {
            return base.Channel.Combine(Relaxvalue, Safetyvalue);
        }
        
        public System.Threading.Tasks.Task<double> CombineAsync(double Relaxvalue, int Safetyvalue) {
            return base.Channel.CombineAsync(Relaxvalue, Safetyvalue);
        }
    }
}
