//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripBookingWebApp.BookingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookingService.IAirportAndHotelService")]
    public interface IAirportAndHotelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirportAndHotelService/GetFlightBookings", ReplyAction="http://tempuri.org/IAirportAndHotelService/GetFlightBookingsResponse")]
        string[][] GetFlightBookings(string originLatitude, string originLongitude, string destinationLatitude, string destinationLongitude, string departDate, string returnDate, string adults, string children);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirportAndHotelService/GetFlightBookings", ReplyAction="http://tempuri.org/IAirportAndHotelService/GetFlightBookingsResponse")]
        System.Threading.Tasks.Task<string[][]> GetFlightBookingsAsync(string originLatitude, string originLongitude, string destinationLatitude, string destinationLongitude, string departDate, string returnDate, string adults, string children);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirportAndHotelService/GetHotelBookings", ReplyAction="http://tempuri.org/IAirportAndHotelService/GetHotelBookingsResponse")]
        string[][] GetHotelBookings(string latitude, string longitude, string checkInDate, string checkOutDate, string rooms, string adults, string children);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirportAndHotelService/GetHotelBookings", ReplyAction="http://tempuri.org/IAirportAndHotelService/GetHotelBookingsResponse")]
        System.Threading.Tasks.Task<string[][]> GetHotelBookingsAsync(string latitude, string longitude, string checkInDate, string checkOutDate, string rooms, string adults, string children);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAirportAndHotelServiceChannel : TripBookingWebApp.BookingService.IAirportAndHotelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AirportAndHotelServiceClient : System.ServiceModel.ClientBase<TripBookingWebApp.BookingService.IAirportAndHotelService>, TripBookingWebApp.BookingService.IAirportAndHotelService {
        
        public AirportAndHotelServiceClient() {
        }
        
        public AirportAndHotelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AirportAndHotelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirportAndHotelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirportAndHotelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[][] GetFlightBookings(string originLatitude, string originLongitude, string destinationLatitude, string destinationLongitude, string departDate, string returnDate, string adults, string children) {
            return base.Channel.GetFlightBookings(originLatitude, originLongitude, destinationLatitude, destinationLongitude, departDate, returnDate, adults, children);
        }
        
        public System.Threading.Tasks.Task<string[][]> GetFlightBookingsAsync(string originLatitude, string originLongitude, string destinationLatitude, string destinationLongitude, string departDate, string returnDate, string adults, string children) {
            return base.Channel.GetFlightBookingsAsync(originLatitude, originLongitude, destinationLatitude, destinationLongitude, departDate, returnDate, adults, children);
        }
        
        public string[][] GetHotelBookings(string latitude, string longitude, string checkInDate, string checkOutDate, string rooms, string adults, string children) {
            return base.Channel.GetHotelBookings(latitude, longitude, checkInDate, checkOutDate, rooms, adults, children);
        }
        
        public System.Threading.Tasks.Task<string[][]> GetHotelBookingsAsync(string latitude, string longitude, string checkInDate, string checkOutDate, string rooms, string adults, string children) {
            return base.Channel.GetHotelBookingsAsync(latitude, longitude, checkInDate, checkOutDate, rooms, adults, children);
        }
    }
}
